// <auto-generated />
using System;
using Homo.FarmApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FarmApi.Migrations
{
    [DbContext(typeof(FarmDbContext))]
    partial class FarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Homo.FarmApi.Strawberry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("BornFrom")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InitialState")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Label");

                    b.ToTable("Strawberry");
                });

            modelBuilder.Entity("Homo.FarmApi.StrawberryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Flower")
                        .HasColumnType("int");

                    b.Property<int>("FlowerBud")
                        .HasColumnType("int");

                    b.Property<int>("Fruit")
                        .HasColumnType("int");

                    b.Property<int>("IsFertilize")
                        .HasColumnType("int");

                    b.Property<int>("IsPruning")
                        .HasColumnType("int");

                    b.Property<int>("IsRepotting")
                        .HasColumnType("int");

                    b.Property<int>("LeavesBud")
                        .HasColumnType("int");

                    b.Property<int>("OldLeaves")
                        .HasColumnType("int");

                    b.Property<int>("Stolon")
                        .HasColumnType("int");

                    b.Property<long>("StrawberryId")
                        .HasColumnType("bigint");

                    b.Property<int>("TenderLeaves")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Flower");

                    b.HasIndex("FlowerBud");

                    b.HasIndex("Fruit");

                    b.HasIndex("IsFertilize");

                    b.HasIndex("IsPruning");

                    b.HasIndex("IsRepotting");

                    b.HasIndex("LeavesBud");

                    b.HasIndex("OldLeaves");

                    b.HasIndex("Stolon");

                    b.HasIndex("StrawberryId");

                    b.HasIndex("TenderLeaves");

                    b.ToTable("StrawberryLog");
                });
#pragma warning restore 612, 618
        }
    }
}
